/* #undef LIBVNCSERVER_BUILD_LINUX */
#define LIBVNCSERVER_BUILD_WIN32 1
/* #undef LIBVNCSERVER_BUILD_APPLE */

#define LIBVNCSERVER_HOST_X86 1
/* #undef LIBVNCSERVER_HOST_X86_64 */

/* #undef LIBVNCSERVER_HAVE_ARPA_INET_H */
#define LIBVNCSERVER_HAVE_FCNTL_H 1
#define LIBVNCSERVER_HAVE_LIMITS_H 1
#define LIBVNCSERVER_HAVE_MEMORY_H 1
/* #undef LIBVNCSERVER_HAVE_NETDB_H */
/* #undef LIBVNCSERVER_HAVE_NETINET_IN_H */
#define LIBVNCSERVER_HAVE_STDINT_H 1
#define LIBVNCSERVER_HAVE_STDLIB_H 1
#define LIBVNCSERVER_HAVE_STDBOOL_H 1
#define LIBVNCSERVER_HAVE_STRING_H 1
#define LIBVNCSERVER_HAVE_STRINGS_H 1
/* #undef LIBVNCSERVER_HAVE_SYS_IOCTL_H */
/* #undef LIBVNCSERVER_HAVE_SYS_SOCKET_H */
#define LIBVNCSERVER_HAVE_SYS_TIME_H 1
#define LIBVNCSERVER_HAVE_SYS_TIMEB_H 1
#define LIBVNCSERVER_HAVE_SYS_STAT_H 1
/* #undef LIBVNCSERVER_HAVE_SYSLOG_H */
#define LIBVNCSERVER_HAVE_UNISTD_H 1
/* #undef LIBVNCSERVER_HAVE_PWD_H */
#define LIBVNCSERVER_HAVE_SYS_TYPES_H 1
/* #undef LIBVNCSERVER_HAVE_UTMPX_H */
/* #undef LIBVNCSERVER_HAVE_SYS_WAIT_H */
#define LIBVNCSERVER_HAVE_TIME_H 1
#define LIBVNCSERVER_HAVE_ERRNO_H 1
#define LIBVNCSERVER_HAVE_PTHREAD_H 1
/* #undef LIBVNCSERVER_HAVE_SYS_IPC_H */
/* #undef LIBVNCSERVER_HAVE_SYS_SHM_H */
#define LIBVNCSERVER_HAVE_STDARG_H 1
#define LIBVNCSERVER_HAVE_SIGNAL_H 1
#define LIBVNCSERVER_HAVE_CTYPE_H 1
#define LIBVNCSERVER_HAVE_PROCESS_H 1
/* #undef LIBVNCSERVER_HAVE_DLFCN_H */
#define LIBVNCSERVER_HAVE_INTTYPES_H 1
/* #undef LIBVNCSERVER_HAVE_VFORK_H */
/* #undef LIBVNCSERVER_HAVE_LINUX_FB_H */
/* #undef LIBVNCSERVER_HAVE_LINUX_INPUT_H */
/* #undef LIBVNCSERVER_HAVE_LINUX_UINPUT_H */
/* #undef LIBVNCSERVER_HAVE_LINUX_VIDEODEV_H */


#define LIBVNCSERVER_HAVE_FTIME 1
/* #undef LIBVNCSERVER_HAVE_MKFIFO */
#define LIBVNCSERVER_HAVE_DUP2 1
#define LIBVNCSERVER_HAVE_FLOOR 1
/* #undef LIBVNCSERVER_HAVE_GETHOSTBYNAME */
/* #undef LIBVNCSERVER_HAVE_GETHOSTNAME */
#define LIBVNCSERVER_HAVE_GETTIMEOFDAY 1
/* #undef LIBVNCSERVER_HAVE_INET_NTOA */
#define LIBVNCSERVER_HAVE_MEMCMP 1
#define LIBVNCSERVER_HAVE_MEMMOVE 1
#define LIBVNCSERVER_HAVE_MEMCPY 1
#define LIBVNCSERVER_HAVE_MEMSET 1
/* #undef LIBVNCSERVER_HAVE_MMAP */
#define LIBVNCSERVER_HAVE_POW 1
#define LIBVNCSERVER_HAVE_PUTENV 1
/* #undef LIBVNCSERVER_HAVE_SELECT */
/* #undef LIBVNCSERVER_HAVE_SOCKET */
#define LIBVNCSERVER_HAVE_STRCHR 1
#define LIBVNCSERVER_HAVE_STRDUP 1
#define LIBVNCSERVER_HAVE_STRERROR 1
#define LIBVNCSERVER_HAVE_STRPBRK 1
#define LIBVNCSERVER_HAVE_STRRCHR 1
#define LIBVNCSERVER_HAVE_STRSTR 1
/* #undef LIBVNCSERVER_HAVE_UNAME */
/* #undef LIBVNCSERVER_HAVE_SETSID */
/* #undef LIBVNCSERVER_HAVE_GETPWUID */
/* #undef LIBVNCSERVER_HAVE_GETPWNAM */
/* #undef LIBVNCSERVER_HAVE_GETUID */
/* #undef LIBVNCSERVER_HAVE_GETEUID */
/* #undef LIBVNCSERVER_HAVE_WAITPID */
/* #undef LIBVNCSERVER_HAVE_SETUTXENT */
/* #undef LIBVNCSERVER_HAVE_SETPGRP */
/* #undef LIBVNCSERVER_HAVE_SETEUID */
/* #undef LIBVNCSERVER_HAVE_GRANTPT */
/* #undef LIBVNCSERVER_HAVE_GETSPNAM */
/* #undef LIBVNCSERVER_HAVE_INITGROUPS */


/* x11vnc configuration */
#define LIBVNCSERVER_ALLOW24BPP
#define LIBVNCSERVER_BACKCHANNEL
/* #undef LIBVNCSERVER_HAVE_X11 */
/* #undef LIBVNCSERVER_HAVE_XSHM */
/* #undef LIBVNCSERVER_HAVE_XTEST */
/* #undef LIBVNCSERVER_HAVE_LIBXINERAMA */
/* #undef LIBVNCSERVER_HAVE_LIBXRANDR */
/* #undef LIBVNCSERVER_HAVE_LIBXFIXES */
/* #undef LIBVNCSERVER_HAVE_LIBXDAMAGE */
/* #undef LIBVNCSERVER_HAVE_SOLARIS_XREADSCREEN */
/* #undef LIBVNCSERVER_HAVE_FBPM */
/* #undef LIBVNCSERVER_HAVE_DPMS */
/* #undef LIBVNCSERVER_HAVE_XTESTGRABCONTROL */
/* #undef LIBVNCSERVER_HAVE_RECORD */
/* #undef LIBVNCSERVER_HAVE_IRIX_XREADDISPLAY */
/* #undef LIBVNCSERVER_HAVE_XKBLIB_H */
/* #undef LIBVNCSERVER_HAVE_XKEYBOARD */
/* #undef LIBVNCSERVER_HAVE_LIBCRYPT */
#define LIBVNCSERVER_HAVE_LIBPTHREAD 1
#define LIBVNCSERVER_HAVE_TLS 1
