/* #undef VERITABLE_BUILD_LINUX */
#define VERITABLE_BUILD_WIN32 1
/* #undef VERITABLE_BUILD_APPLE */

#define VERITABLE_HOST_X86 1
/* #undef VERITABLE_HOST_X86_64 */

/* #undef VERITABLE_HAVE_ARPA_INET_H */
#define VERITABLE_HAVE_FCNTL_H 1
#define VERITABLE_HAVE_LIMITS_H 1
#define VERITABLE_HAVE_MEMORY_H 1
/* #undef VERITABLE_HAVE_NETDB_H */
/* #undef VERITABLE_HAVE_NETINET_IN_H */
#define VERITABLE_HAVE_STDINT_H 1
#define VERITABLE_HAVE_STDLIB_H 1
#define VERITABLE_HAVE_STDBOOL_H 1
#define VERITABLE_HAVE_STRING_H 1
#define VERITABLE_HAVE_STRINGS_H 1
/* #undef VERITABLE_HAVE_SYS_IOCTL_H */
/* #undef VERITABLE_HAVE_SYS_SOCKET_H */
#define VERITABLE_HAVE_SYS_TIME_H 1
#define VERITABLE_HAVE_SYS_TIMEB_H 1
#define VERITABLE_HAVE_SYS_STAT_H 1
/* #undef VERITABLE_HAVE_SYSLOG_H */
#define VERITABLE_HAVE_UNISTD_H 1
/* #undef VERITABLE_HAVE_PWD_H */
#define VERITABLE_HAVE_SYS_TYPES_H 1
/* #undef VERITABLE_HAVE_UTMPX_H */
/* #undef VERITABLE_HAVE_SYS_WAIT_H */
#define VERITABLE_HAVE_TIME_H 1
#define VERITABLE_HAVE_ERRNO_H 1
#define VERITABLE_HAVE_PTHREAD_H 1
/* #undef VERITABLE_HAVE_SYS_IPC_H */
/* #undef VERITABLE_HAVE_SYS_SHM_H */
#define VERITABLE_HAVE_STDARG_H 1
#define VERITABLE_HAVE_SIGNAL_H 1
#define VERITABLE_HAVE_CTYPE_H 1
#define VERITABLE_HAVE_PROCESS_H 1
/* #undef VERITABLE_HAVE_DLFCN_H */
#define VERITABLE_HAVE_INTTYPES_H 1
/* #undef VERITABLE_HAVE_VFORK_H */
/* #undef VERITABLE_HAVE_LINUX_FB_H */
/* #undef VERITABLE_HAVE_LINUX_INPUT_H */
/* #undef VERITABLE_HAVE_LINUX_UINPUT_H */
/* #undef VERITABLE_HAVE_LINUX_VIDEODEV_H */


#define VERITABLE_HAVE_FTIME 1
/* #undef VERITABLE_HAVE_MKFIFO */
#define VERITABLE_HAVE_DUP2 1
#define VERITABLE_HAVE_FLOOR 1
/* #undef VERITABLE_HAVE_GETHOSTBYNAME */
/* #undef VERITABLE_HAVE_GETHOSTNAME */
#define VERITABLE_HAVE_GETTIMEOFDAY 1
/* #undef VERITABLE_HAVE_INET_NTOA */
#define VERITABLE_HAVE_MEMCMP 1
#define VERITABLE_HAVE_MEMMOVE 1
#define VERITABLE_HAVE_MEMCPY 1
#define VERITABLE_HAVE_MEMSET 1
/* #undef VERITABLE_HAVE_MMAP */
#define VERITABLE_HAVE_POW 1
#define VERITABLE_HAVE_PUTENV 1
/* #undef VERITABLE_HAVE_SELECT */
/* #undef VERITABLE_HAVE_SOCKET */
#define VERITABLE_HAVE_STRCHR 1
#define VERITABLE_HAVE_STRDUP 1
#define VERITABLE_HAVE_STRERROR 1
#define VERITABLE_HAVE_STRPBRK 1
#define VERITABLE_HAVE_STRRCHR 1
#define VERITABLE_HAVE_STRSTR 1
/* #undef VERITABLE_HAVE_UNAME */
/* #undef VERITABLE_HAVE_SETSID */
/* #undef VERITABLE_HAVE_GETPWUID */
/* #undef VERITABLE_HAVE_GETPWNAM */
/* #undef VERITABLE_HAVE_GETUID */
/* #undef VERITABLE_HAVE_GETEUID */
/* #undef VERITABLE_HAVE_WAITPID */
/* #undef VERITABLE_HAVE_SETUTXENT */
/* #undef VERITABLE_HAVE_SETPGRP */
/* #undef VERITABLE_HAVE_SETEUID */
/* #undef VERITABLE_HAVE_GRANTPT */
/* #undef VERITABLE_HAVE_GETSPNAM */
/* #undef VERITABLE_HAVE_INITGROUPS */


/* x11vnc configuration */
#define VERITABLE_ALLOW24BPP
#define VERITABLE_BACKCHANNEL
/* #undef VERITABLE_HAVE_X11 */
/* #undef VERITABLE_HAVE_XSHM */
/* #undef VERITABLE_HAVE_XTEST */
/* #undef VERITABLE_HAVE_LIBXINERAMA */
/* #undef VERITABLE_HAVE_LIBXRANDR */
/* #undef VERITABLE_HAVE_LIBXFIXES */
/* #undef VERITABLE_HAVE_LIBXDAMAGE */
/* #undef VERITABLE_HAVE_SOLARIS_XREADSCREEN */
/* #undef VERITABLE_HAVE_FBPM */
/* #undef VERITABLE_HAVE_DPMS */
/* #undef VERITABLE_HAVE_XTESTGRABCONTROL */
/* #undef VERITABLE_HAVE_RECORD */
/* #undef VERITABLE_HAVE_IRIX_XREADDISPLAY */
/* #undef VERITABLE_HAVE_XKBLIB_H */
/* #undef VERITABLE_HAVE_XKEYBOARD */
/* #undef VERITABLE_HAVE_LIBCRYPT */
#define VERITABLE_HAVE_LIBPTHREAD 1
#define VERITABLE_HAVE_TLS 1
